# Generated by Django 5.2.1 on 2025-06-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(blank=True, choices=[('remote', 'Remote'), ('on-site', 'On-site'), ('hybrid', 'Hybrid')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='short_description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
