# Generated by Django 5.2.1 on 2025-06-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notification_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, default='New notification', max_length=30, null=True),
        ),
    ]
