# Generated by Django 5.2.1 on 2025-06-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_bio_user_github_url_user_linkedin_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='crypto_wallet_address',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
    ]
